version: '3.9'

services:
  api:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    restart: always
    ports:
      - 3000:3000
    command: yarn start:dev
    env_file:
      - ./.env
    extra_hosts:
      # set INTERNAL_HOST=host.docker.internal in .env on linux
      - ${INTERNAL_HOST:-INTERNAL_HOST}:host-gateway
